homeassistant:
  # Customize
  customize: !include customize.yaml
  # ------------------------------------------------------------
  # Packages
  packages: !include_dir_named packages/
  # ------------------------------------------------------------

# Frontend
frontend:
  # Themes
  themes: !include_dir_merge_named themes
  # ------------------------------------------------------------

# Main Config
config:
system_health:
api:
map:
mobile_app: 
sun:  
media_source:
# --------------------------------------------------------------

# Recorder
logger:
  default: info
  # ------------------------------------------------------------
  # AUTOMATION DEBUG
  # logs:
  #   homeassistant.components.automation: debug
  # ------------------------------------------------------------
zeroconf:
  default_interface: true 
  # ------------------------------------------------------------

# Calendar
calendar:
  # Casa
  - platform: caldav
    url: !secret calendar_url
    username: !secret calendar_user
    password: !secret calendar_psw
    calendars:
      - 'Casa'
    # ----------------------------------------------------------

# UI
lovelace:
  # MODE
  mode: storage
  # ------------------------------------------------------------
  # Dashoards
  dashboards:
    #Floorplan UI
    ndr-floorplan:
      mode: yaml
      title: NdR Floorplan UI
      icon: mdi:tablet
      show_in_sidebar: true
      filename: ndr_floorplan.yaml
    # ------------------------------------------------------------

#LG WebOS
webostv:
  host: 192.168.1.120
  name: TV Sala
  turn_on_action:
    service: media_player.turn_on
    entity_id: media_player.tv_lg_sala #Entit√† creata con SmartIR per accendere la TV con Broadlink
  # ------------------------------------------------------------

# SmartIR
smartir:
# --------------------------------------------------------------

# Media Player  
media_player:
  - platform: smartir
    name: TV LG Sala
    device_code: 180891
    controller_data: remote.rm3_sala_remote
    power_sensor: media_player.tv_sala #Usa l'integrazione WebOS per rilevare acceso/spento
  # ------------------------------------------------------------

# Caddy
http:
  use_x_forwarded_for: true
  trusted_proxies: 
    - 192.168.1.150
  # ------------------------------------------------------------

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api
    allowed_chat_ids:
      - !secret chat_id_andre
      - !secret chat_id_mary
      - !secret chat_id_casa   
  # ------------------------------------------------------------

# Notifiche
notify:
  # Andrea
  - name: Andrea
    platform: telegram
    chat_id: !secret chat_id_andre
  # ------------------------------------------------------------
  # Mary
  - name: Mary
    platform: telegram
    chat_id: !secret chat_id_mary
  # ------------------------------------------------------------
  # Casa
  - name: casa
    platform: telegram
    chat_id: !secret chat_id_casa 
  # ------------------------------------------------------------
  # Famiglia
  - name: famiglia
    platform: group
    services:
      - service: andrea
      - service: mary
# --------------------------------------------------------------
#Add-on
browser_mod:
  prefix: "browser_mod_"
  devices:
    8d873a9e-736098d3:
      name: pc_studio
    30f58c9d-c0130b01:
      name: ipad
    9ee1123f-b1245125:
      name: macbook_chrome
  # disable:
  #   - all
  # ------------------------------------------------------------

# Text to speech
tts:
  # Google
  - platform: google_translate
    service_name: google_say
    language: 'it'
  # ------------------------------------------------------------

# Tracker
device_tracker:
  # Fritz!Box
- platform: fritz
  host: 192.168.1.1
  consider_home: 180
  interval_seconds: 30
  new_device_defaults:
    track_new_devices: false
  # ------------------------------------------------------------